# Generated by Django 4.2.7 on 2023-11-23 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_system_type', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('sem', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('SUMMER', 'SUMMER')], max_length=10, null=True)),
                ('school_year', models.CharField(blank=True, max_length=9, null=True)),
                ('revision_status', models.CharField(default='1st Draft', max_length=50)),
                ('revision_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vision_Itemize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_itemize', models.TextField()),
                ('syllabus_template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.syllabus_template')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField()),
                ('default', models.BooleanField(default=False)),
                ('syllabus_template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.syllabus_template')),
            ],
        ),
        migrations.CreateModel(
            name='Term_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=50)),
                ('term_percentage', models.IntegerField(blank=True, null=True)),
                ('grading_system_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.grading_system')),
            ],
        ),
        migrations.CreateModel(
            name='Term_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_description', models.CharField(max_length=255)),
                ('percentage', models.SmallIntegerField(blank=True, null=True)),
                ('lecture_percentage', models.SmallIntegerField(blank=True, null=True)),
                ('laboratory_percentage', models.SmallIntegerField(blank=True, null=True)),
                ('term_grade_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.term_grade')),
            ],
        ),
        migrations.CreateModel(
            name='Percentage_Grade_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_range', models.SmallIntegerField(blank=True, null=True)),
                ('max_range', models.SmallIntegerField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('grading_system_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.grading_system')),
            ],
        ),
        migrations.CreateModel(
            name='Mission_Itemize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_itemize', models.TextField()),
                ('default', models.BooleanField(default=False)),
                ('syllabus_template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.syllabus_template')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('default', models.BooleanField(default=False)),
                ('syllabus_template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.syllabus_template')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_name', models.CharField(max_length=250)),
                ('default', models.BooleanField(default=False)),
                ('syllabus_template_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.syllabus_template')),
            ],
        ),
        migrations.AddField(
            model_name='grading_system',
            name='syllabus_template_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.syllabus_template'),
        ),
        migrations.CreateModel(
            name='Goal_Itemize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_itemize', models.TextField()),
                ('syllabus_template_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.syllabus_template')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('syllabus_template_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.syllabus_template')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_outcome', models.TextField()),
                ('syllabus_template_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_template.syllabus_template')),
            ],
        ),
    ]
