# Generated by Django 4.2.7 on 2023-11-23 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('course_learning_outcomes', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus_AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_source', models.TextField(blank=True, null=True)),
                ('raw_topics', models.TextField(blank=True, null=True)),
                ('raw_course_outline', models.TextField(blank=True)),
                ('raw_course_learning_outcomes', models.TextField(blank=True, null=True)),
                ('raw_course_learning_outcomes_ai_with_letters', models.TextField(blank=True, null=True)),
                ('raw_first_prompt', models.TextField(blank=True, null=True)),
                ('raw_first_response', models.TextField(blank=True, null=True)),
                ('raw_second_prompt', models.TextField(blank=True, null=True)),
                ('raw_second_response', models.TextField(blank=True, null=True)),
                ('first_time_processing', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Values_Intended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField()),
                ('course_outline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.course_outline')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.TextField()),
                ('syllabus_ai_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.syllabus_ai')),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('syllabus_ai_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.syllabus_ai')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome_Based_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oba', models.TextField()),
                ('course_outline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.course_outline')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence_of_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eoo', models.TextField()),
                ('course_outline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.course_outline')),
            ],
        ),
        migrations.CreateModel(
            name='Desired_Student_Learning_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dslo', models.TextField()),
                ('course_outline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.course_outline')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Rubric_Mid_Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_course_rubric_defense_ai', models.TextField(blank=True)),
                ('title', models.CharField(max_length=150)),
                ('criteria', models.CharField(max_length=150)),
                ('beginner', models.CharField(max_length=255)),
                ('capable', models.CharField(max_length=255)),
                ('accomplished', models.CharField(max_length=255)),
                ('expert', models.CharField(max_length=255)),
                ('syllabus_ai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.syllabus_ai')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Rubric_Final_Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_course_rubric_defense_ai', models.TextField(blank=True)),
                ('title', models.CharField(max_length=150)),
                ('criteria', models.CharField(max_length=150)),
                ('one', models.CharField(max_length=150)),
                ('two', models.CharField(max_length=150)),
                ('three', models.CharField(max_length=150)),
                ('four', models.CharField(max_length=150)),
                ('five', models.CharField(max_length=150)),
                ('syllabus_ai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.syllabus_ai')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('criteria', models.CharField(blank=True, max_length=150, null=True)),
                ('beginner', models.CharField(blank=True, max_length=150, null=True)),
                ('capable', models.CharField(blank=True, max_length=150, null=True)),
                ('accomplished', models.CharField(blank=True, max_length=150, null=True)),
                ('expert', models.CharField(blank=True, max_length=150, null=True)),
                ('syllabus_ai_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.syllabus_ai')),
            ],
        ),
        migrations.AddField(
            model_name='course_outline',
            name='syllabus_ai_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.syllabus_ai'),
        ),
        migrations.CreateModel(
            name='Course_Learning_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_learning_outcome', models.TextField(blank=True, null=True)),
                ('syllabus_ai_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.syllabus_ai')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_content', models.TextField()),
                ('course_outline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.course_outline')),
            ],
        ),
    ]
