# Generated by Django 4.2.7 on 2023-11-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Rubric_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(blank=True, max_length=150, null=True)),
                ('beginner', models.CharField(blank=True, max_length=150, null=True)),
                ('capable', models.CharField(blank=True, max_length=150, null=True)),
                ('accomplished', models.CharField(blank=True, max_length=150, null=True)),
                ('expert', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course_rubric_mid_defense',
            name='syllabus_ai_id',
        ),
        migrations.RemoveField(
            model_name='course_rubric',
            name='accomplished',
        ),
        migrations.RemoveField(
            model_name='course_rubric',
            name='beginner',
        ),
        migrations.RemoveField(
            model_name='course_rubric',
            name='capable',
        ),
        migrations.RemoveField(
            model_name='course_rubric',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='course_rubric',
            name='expert',
        ),
        migrations.AddField(
            model_name='course_rubric',
            name='raw_source_course_rubric_ai',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Course_Rubric_Final_Defense',
        ),
        migrations.DeleteModel(
            name='Course_Rubric_Mid_Defense',
        ),
        migrations.AddField(
            model_name='course_rubric_item',
            name='course_rubric_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus_ai.course_rubric'),
        ),
    ]
