# Generated by Django 4.2.4 on 2023-11-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_ai', '0002_course_rubric_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus_ai',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Filipino', 'Filipino')], default='English', max_length=10),
        ),
    ]
