# Generated by Django 4.2.4 on 2023-11-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_ai', '0004_remove_syllabus_ai_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus_ai',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Filipino', 'Filipino')], default='English', max_length=10),
        ),
    ]
